config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  devise_for :users

  resources :users
  resources :posts
  resources :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
    
    validates :body, presence: true, length: { minimum: 1 }
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, dependent: :destroy

    belongs_to :user
  
    validates :title, presence: true, length: { minimum: 3 }
    validates :body, presence: true, length: { minimum: 30 }

    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.jpg"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

#     has_attached_file :avatar, styles: {
#     thumb: '100x100>',
#     square: '200x200#',
#     medium: '300x300>'
#   }

#   # Validate the attached image is image/jpg, image/png, etc
#   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

    def index
      @comments = Comment.all
    end 

    def new
      @comment = Comment.new
    end

    def create
      @comment = Comment.new(comment_params)
      if @comment.save
        flash[:success] = "Comment has been added"
      else 
        flash[:danger] = "You can't do this"
      end
      redirect_back(fallback_location: root_path)
    end

    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy

      flash[:success] = "Comment deleted" 
      redirect_back(fallback_location: root_path)
    end

    private

    def comment_params
      if current_user
        params.require(:comment).permit!
      end
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_post, only: [:show, :edit, :update, :destroy]
  
    def index
      @posts = Post.order('created_at DESC').page(params[:page]).per(3)
    end
  
    def show
    end
  
    def new
      @post = Post.new
    end
  
    def create
      @user = current_user
      @post = @user.posts.build(allowed_params)
  
      if @post.save
        flash[:success] = "Created new post"
        redirect_to @post
      else
        render 'new'
      end
    end
  
    def edit
      redirect_to posts_path unless @post.user == current_user
    end
  
    def update
      if @post.user == current_user
        if @post.update_attributes(allowed_params)
          flash[:success] = "Updated post"
          redirect_to @post
        else
          render 'edit'
        end
      else
        redirect_to posts_path
        flash[:notice] = "You can't do this"
      end
    end
  
    def destroy
      if @post.user == current_user
        @post.destroy
        redirect_to posts_path
        flash[:success] = "deleted post"
      else
        redirect_to root_path
        flash[:danger] = "You can't do this"
      end
    end
  
    private
      def allowed_params
        params.require(:post).permit(:title, :body, :avatar)
      end
  
      def find_post
          @post = Post.find(params[:id])
      end
  end
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home    
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:edit, :update, :show, :delete]
  
    def index
        @users = User.order('created_at DESC')
    end
  
    def show
        @user = User.find(params[:id])
        @posts = @user.posts.order('created_at DESC')
    end
  
    def new
        @user = User.new
    end
  
    def create
        @user = User.create(params[:user].permit!)
        redirect_to user_path(@user.id) if @user.persisted?
    end
  
    private
  
    def find_user
        @user = User.find(params[:id])
    end
  
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for [@comment, Comment.new] do |f| %>
    <div class="form-group">
        <h3 class="title comment-title">Add a comment</h3>
        <%= f.text_area :body, class: 'form-control textarea', rows: 6, placeholder: "Insert your comment here" %>
    </div>

    <%= f.hidden_field :post_id, value: @post.id %>
    <% if user_signed_in? %>
        <%= f.hidden_field :user_id, value: current_user.id %>
    <% end %>
    <%= f.submit 'Save', class: 'button is-link buttonbs' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Spaced Blog</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= favicon_link_tag 'icon.png' %>
    </head>
    <body>

        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <%= value %>
        </div>
        <% end %>

    <div class="hero-head">
        <header class="nav has-shadow">
            <div class="container">
                <div class="nav-left">
                        <%= link_to image_tag("logo.png"), root_path, class: "is-logo" %>
                </div>
                <span class="nav-toggle">
                    <span></span>
                    <span></span>
                    <span></span>
                </span>
                <div class="nav-right nav-menu">
                 <% if current_user %>
                           <%= link_to 'Logout', destroy_user_session_path, class:"nav-item", method: :delete %>
                          <span class="nav-item"> <%= link_to 'Users', users_path, class:"nav-item" %></span>
                          <span class="nav-item"> <%= link_to 'New post', new_post_path, class:"button is-primary" %></span>
                         <% else %>
                            <span class="nav-item"> <%= link_to 'Users', users_path, class:"nav-item" %></span>
                            <%= link_to 'Login', new_user_session_path, class:"nav-item" %>
                         <% end %>
                </div>
            </div>
        </header>
    </div>

          <div class="container">
              <%= yield %>
          </div>


    </body>
</html>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Spaced Blog</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= favicon_link_tag 'icon.png' %>
    </head>
    <body>

        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <%= value %>
        </div>
        <% end %>

    <div class="hero-head">
        <header class="nav has-shadow">
            <div class="container">
                <div class="nav-left">
                    <a class="nav-item" href="#" title="Spaced Blog on Ruby">
                        <%= link_to image_tag("logo.png"), root_path, class: "is-logo" %>
                    </a>
                </div>
                <span class="nav-toggle">
                    <span></span>
                    <span></span>
                    <span></span>
                </span>
                <div class="nav-right nav-menu">
                 <% if current_user %>
                           <%= link_to 'Logout', destroy_user_session_path, class:"nav-item", method: :delete %>
                          <span class="nav-item"> <%= link_to 'New post', new_post_path, class:"button is-primary" %></span>
                         <% else %>
                            <%= link_to 'Login', new_user_session_path, class:"nav-item" %>
                         <% end %>
                </div>
            </div>
        </header>
    </div>

          <div class="container">
              <%= yield %>
          </div>


    </body>
</html>

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
    
        <div class="form-group">
            <%= f.label :title, class: 'control-label label'%>
            <%= f.text_field :title, class: 'form-control input', placeholder: "Title of your article", type:"Text" %>
        </div>

        <div class="form-group">
            <%= f.label :body, class: 'control-label label' %>
            <%= f.text_area :body, class: 'form-control form-noodle textarea', rows: 6, placeholder: "Content of your article" %>
        </div>

        <%= f.submit 'Save', class: 'button is-link buttonbs' %>
<% end %>

app/views/posts/_post.html.erb
            <div class="item article-user">
                <%= link_to post_path(post.id) do %>
             <%= image_tag(post.avatar.url(:medium), class:"user-article-photo item-figure image is2by1") %>
                     <% end %>
            <div class="item-content">
                <div class="level">
                    <h2 class="title item-title"><%= link_to truncate(post.title, :length => 80), post_path(post.id) %></h2>
                </div>
                <div class="item-description">
                <p class="blog-body"><%= truncate(post.body, :length => 200) %></p>
                  <%= link_to t('Read'), post_path(post.id), class: "article__link" %>
                </div>
            </div>
            </div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
    <p><%= link_to 'Cancel', post_path(@post) %></p>
    <%= render 'form', post: @post %>
    <br />
    <p><%= link_to 'Delete post', @post, method: :delete, data: {confirm: "Are you sure you want to delete this permanently?"}, class: 'button is-danger buttonbs' %></p>

app/views/posts/index.html.erb
    <div class="columns">
        <% @posts.each do |p| %>
        <div class="column">
            <div class="item">
                <%= link_to post_path(p.id) do %>
             <%= image_tag(p.avatar.url(:medium), class:"item-figure image is2by1") %>
                     <% end %>
            <div class="item-content">
                <div class="level">
                    <h2 class="title item-title"><%= link_to truncate(p.title, :length => 80), post_path(p.id) %></h2>
                </div>
                <div class="item-description">
                <p class="blog-body"><%= truncate(p.body, :length => 200) %></p>
                 <%= link_to "Read more", post_path(p.id), class:"is-primary" %>
                </div>
            </div>
            </div>
        </div>
        <% end %>
    </div>
    <div class="columns is-mobile is-centered">
       <div class="column is-half is-offset-4">
            <%= paginate(@posts) %>
        </div>
    </div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
    <div class="columns">
        <div class="column">
            <div class="item">
            <%= image_tag(@post.avatar.url(:medium)) %>
            <div class="item-content">
                <div class="level">
                    <div class="level-left">
                        <h2 class="title item-title"><%= @post.title %></h2>
                        <span><%= content_tag(:small, link_to('Edit this article', edit_post_path(@post), class:"edit-btn button is-success is-large")) if @post.user == current_user %></span>
                    </div>
                    <div class="item-author button">Posted at <%= @post.created_at.strftime("%H:%M:%S") %> by <%= @post.user.email %></div>
                </div>
                <div class="item-description">
                <p class="article-body"><%= @post.body %></p>
                </div>
            </div>
            </div>
        </div>
    </div>

    <h3>Comment</h3>

    <ul class="comments">
        <% @post.comments.each do |p| %>
                <li>
                    <p><%= p.body %></p>
                </li>
                    <div class="item-author button">Posted at <%= p.created_at.strftime("%H:%M:%S") %> by <%= p.user.email %></div>
                 <% if current_user.id === p.user.id || @post.user.id === current_user.id %>
                    <span class='button is-danger com-delete'><%= link_to t("delete_comment"), comment_path(p.id), method: :delete, data: { confirm: ('Are you sure you want to delete your comment ?') } %></span>
                <% end %>
        <% end %>
    </ul>

    <%= render partial: 'comments/form', locals: { comment: @comment } %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <p><strong>This form contains <%= pluralize(object.errors.count, 'errors') %>.</strong></p>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/users/_user.html.erb
<div class="columns">
    <div class="column">
        <div class="item">
              <%= link_to image_tag("https://api.adorable.io/avatars/285/spaced.png"), user_path(user.id), class: "user-avatar" %>
            <div class="item-content">
                <div class="level">
                   <h2 class="title item-title" style="margin-bottom: 0rem;"><%= user.email %></h2>
                </div>
                <div class="item-description">
                <%= link_to t('View user articles'), user_path(user.id), class: "about__link is-primary" %> 
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<%= render @users %></h2>

app/views/users/show.html.erb
<div class="columns">
    <div class="column">
        <div class="item">
              <%= link_to image_tag("https://api.adorable.io/avatars/285/spaced.png"), users_path, class:"user-avatar" %>
            <div class="item-content">
                <div class="level">
                   <h2><%= @user.email %></h2>
                   <h2 class="title item-title"><%= @posts.count %> articles published</h2>
                </div>
            </div>
        </div>
         <% if @posts.count > 0 %>
        <div class="articles">
          <%= render @posts %>
        </div>
        <% else %>
          <h2></h2>
        <% end %>
</div>